language: objective-c
osx_image: xcode11

before_install:
  - gem install xcpretty

script:
  - swiftlint
  - xcrun simctl list
  - set -o pipefail && xcodebuild -sdk iphonesimulator -project MagicCounterKataIOS.xcodeproj -scheme 'MagicCounterKataIOS' build test | xcpretty -c
