language: objective-c
osx_image: xcode11

before_install:
  - gem install xcpretty

script:
  - swiftlint
  - set -o pipefail && xcodebuild -sdk iphonesimulator -project MagicCounterKataIOS.xcodeproj -scheme 'MagicCounterKataIOS' -destination 'platform=iOS Simulator,name=iPhone 8' build test | xcpretty -c
