language: objective-c
osx_image: xcode11

before_install:
  - gem install xcpretty

script:
  - swiftlint
  - xcrun instruments -s devices
  - set -o pipefail && xcodebuild -sdk iphonesimulator -destination "name=iPhone 8" -project MagicCounterKataIOS.xcodeproj -scheme 'MagicCounterKataIOS' build test | xcpretty -c
