language: objective-c
osx_image: xcode11

before_install:
  - gem install xcpretty

script:
  - swiftlint
  - set -o pipefail && xcodebuild -scheme 'MagicCounterKataIOS' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' build test CODE_SIGN_IDENTITY=- | xcpretty -c
